;
; ""
; by author
;
; sdfg
;
; Generated by blue 0.125.0 (http://csounds.com/stevenyi/blue/index.html)
;

<CsoundSynthesizer>

<CsInstruments>
sr=44100
ksmps=1
nchnls=2

0dbfs = 1







	instr 1	;Keyboard Control
prints "Please type something"
knum, kdown sensekey

if (kdown==1) then 
printks "\nThe something you pressed was:%d", 0, knum
endif
	endin


</CsInstruments>

<CsScore>

f 1  0  256  -17   0  0  

i1 0 3600





e

</CsScore>

</CsoundSynthesizer>