/*	reverb2 for Csound coded by Paris Smaragdis		*/
/*	Berklee College of Music Csound development team	*/
/*	Copyright (c) December 1994.  All rights reserved	*/


MYFLT gc_time[Combs] = {
	FL(1237.0),
	FL(1381.0),
	FL(1607.0),
	FL(1777.0),
	FL(1949.0),
	FL(2063.0)
};

MYFLT gc_gain[Combs] = {
	FL(.822),
	FL(.802),
	FL(.773),
	FL(.753),
	FL(.753),
	FL(.753)
};

MYFLT ga_time[Alpas] = {
	FL(307.0),
	FL(97.0),
	FL(71.0),
	FL(53.0),
	FL(37.)
};

MYFLT ga_gain[Alpas] = {
	FL(.7),
	FL(.7),
	FL(.7),
	FL(.7),
	FL(.7),
};
