f1   0 513 10 1                                                  ;sine
f3  0 513 10 3 1 0 .25 .3 .76
f4   0 513 9  1 1 90                                             ;cosine
f5   0 513 10 1 .2 0 .06 0 .4                                    ;altered sine
f8  0 256 7  0 0 1 128 1 0 -1 128 -1                             ;square
f31 0 513 13 1 1 .9 .8 .7 .6 .5 .4 .3 .2 .1                      ;gen 13 for table look up
f32 0 513 13 1 1 .9 .8 .7 .6 .7 .8 .9 1                          ;gen 13 for table look up

f0 30
