(in-package :stella)
(defobject simple (csound-note)
  (instr dur amp pitch rise decay wavetable)
  (:parameters instr time dur amp pitch rise decay wavetable)
  )
(algorithm simptest simple (length 20)
	   (setf instr "i3")
	   (setf rhythm (item (rhythms e q e q e. s 12 12 12)))
	   (setf dur rhythm)
	   (setf pitch (item (pitches c4 d ef f g a b fs in heap)))
	   (setf amp 16000)
	   (setf rise .01)
	   (setf decay .01)
	   (setf wavetable 1)
	   )
(defparameter *header*
  (header
   "; Notelist for Csound Orchestra Example2"
   "f 1 0 16384 10 1"))
(fheader "example2a.sco" *header*)
(write-cs "simptest" :filename "example2a.sco")
