;
; ""
; by author
;
; 
;
; Generated by blue 0.99.9 (http://csounds.com/stevenyi/blue/index.html)
;

<CsoundSynthesizer>

<CsInstruments>
sr=44100
ksmps=100
nchnls=1







	instr 1	;untitled

ain1	inch	1
out	ain1
	endin


</CsInstruments>

<CsScore>



i1 0 3600



e

</CsScore>

</CsoundSynthesizer>
