// timepoint.h: interface for the timepoint class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_TIMEPOINT_H__0A2F5F60_79E8_454C_8288_43F0A1971157__INCLUDED_)
#define AFX_TIMEPOINT_H__0A2F5F60_79E8_454C_8288_43F0A1971157__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class timepoint  
{
public:
	timepoint();
	virtual ~timepoint();
    float start;
    float end;
};

#endif // !defined(AFX_TIMEPOINT_H__0A2F5F60_79E8_454C_8288_43F0A1971157__INCLUDED_)
