//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CsoundVST.rc
//
#define IDD_MAIN                        101
#define IDB_ANGEL_CONCERT               103
#define IDC_EDIT                        1000
#define IDC_BUTTON_NEW                  1001
#define IDC_BUTTON_OPEN                 1002
#define IDC_BUTTON_SAVE                 1003
#define IDC_BUTTON_SAVE_AS              1004
#define IDC_BUTTON_PERFORM              1005
#define IDC_BUTTON_STOP_PERFORMANCE     1006
#define IDC_BUTTON_OPEN_SOUND           1007
#define IDC_BUTTON_EDIT_ORCHESTEA       1008
#define IDC_BUTTON_EDIT_SCORE           1009
#define IDC_SLIDER1                     1010

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
